version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ""

volumes:
  postgres_data:
