default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: <%= ENV.fetch("DB_HOST", "db") %>  # O nome do host é 'db', mas pode ser sobrescrito pela variável de ambiente.

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000